# Generated by Django 5.1.7 on 2025-03-24 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("occupancy", "0002_device"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceAPIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prefix",
                    models.CharField(editable=False, max_length=16, unique=True),
                ),
                ("key", models.CharField(editable=False, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="occupancy.device",
                    ),
                ),
            ],
        ),
    ]
