# Generated by Django 5.1.7 on 2025-03-26 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_deviceapikey_key"),
        ("occupancy", "0003_deviceimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deviceapikey",
            name="device",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_key",
                to="occupancy.device",
            ),
        ),
    ]
