services:
  innhabit_db:
    image: postgres:latest
    container_name: innhabit_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file: .env
    user: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  valkey:
    image: valkey/valkey:latest
    container_name: valkey
    volumes:
      - valkey:/data
    env_file: .env
    ports:
      - 6379:6379
    restart: unless-stopped

volumes:
  db_data:
  valkey:
