services:
  innhabit_server:
    build: .
    container_name: innhabit_server
    env_file: .env
    ports:
      - 8001:8000
    restart: unless-stopped
    depends_on:
      innhabit_db:
        condition: service_healthy
    links:
      - innhabit_db
    volumes:
      - /var/www/static:/var/www/static

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 81:80
    volumes:
      - /var/www/innhabit/static:/var/www/innhabit/static
      - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - innhabit_server

  innhabit_db:
    image: postgres:latest
    container_name: innhabit_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    env_file: .env
    user: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  db_data:
