services:
  innhabit_server:
    build: .
    container_name: innhabit_server
    env_file: .env
    ports:
      - 8001:8000
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
      - valkey
    volumes:
      - /var/www/static:/var/www/static

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - 81:80
    volumes:
      - /var/www/static:/var/www/static
      - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - django_app

  db:
    extends:
      file: docker-compose.yaml
      service: db
    ports:
      - 5433:5432

volumes:
  db_data:
