# Generated by Django 5.1.7 on 2025-03-24 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("occupancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entrance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="occupancy.entrance",
                    ),
                ),
            ],
        ),
    ]
