# Generated by Django 5.1.7 on 2025-04-01 11:22

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("occupancy", "0003_deviceimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="entrance",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="device",
                to="occupancy.entrance",
            ),
        ),
        migrations.CreateModel(
            name="DeviceSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_box",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=None,
                        null=True,
                        size=4,
                        validators=[django.core.validators.MinLengthValidator(4)],
                    ),
                ),
                (
                    "exit_box",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=None,
                        null=True,
                        size=4,
                        validators=[django.core.validators.MinLengthValidator(4)],
                    ),
                ),
                (
                    "device",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="occupancy.device",
                    ),
                ),
            ],
        ),
    ]
