# Generated by Django 5.1.7 on 2025-05-08 08:41

import occupancy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("occupancy", "0005_testentryevent_testexitevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entryevent",
            name="timestamp",
            field=models.DateTimeField(
                validators=[
                    occupancy.models.validate_not_future,
                    occupancy.models.validate_not_too_old,
                ]
            ),
        ),
        migrations.AlterField(
            model_name="exitevent",
            name="timestamp",
            field=models.DateTimeField(
                validators=[
                    occupancy.models.validate_not_future,
                    occupancy.models.validate_not_too_old,
                ]
            ),
        ),
        migrations.AlterField(
            model_name="testentryevent",
            name="timestamp",
            field=models.DateTimeField(
                validators=[
                    occupancy.models.validate_not_future,
                    occupancy.models.validate_not_too_old,
                ]
            ),
        ),
        migrations.AlterField(
            model_name="testexitevent",
            name="timestamp",
            field=models.DateTimeField(
                validators=[
                    occupancy.models.validate_not_future,
                    occupancy.models.validate_not_too_old,
                ]
            ),
        ),
    ]
