name: Python Server

on:
  push

jobs:
  black:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install black
      run: |
        python -m pip install --upgrade pip
        pip install "black<26"
    - name: Check code formatting with black
      working-directory: innhabitserver
      run: |
        black --diff --check $(git ls-files "*.py")

  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: isort/isort-action@v1
        with:
          configuration: "--check-only --diff --profile black"
          paths: "innhabitserver"

  pylint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install pylint
      run: |
        python3 -m pip install --upgrade pip
        pip install pylint

    - name: Analyse the code with pylint
      working-directory: innhabitserver
      run: |
        pylint --rcfile=.pylintrc $(git ls-files "*.py")

  mypy:
    needs: [black, isort, pylint]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
        cache: pip

    - name: Install dependencies
      working-directory: innhabitserver
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt
    - name: Static type checking with mypy
      working-directory: innhabitserver
      run: |
          mypy innhabitserver

  unittests:
    needs: [black, isort, pylint]
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

        ports:
          - 5432:5432

        # Wait for postgres to start
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    steps:
    - uses: actions/checkout@v4
    - name: Setup Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
        cache: pip

    - name: Install dependencies
      working-directory: innhabitserver
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt
    - name: Run unittests
      working-directory: innhabitserver
      run: |
        python3 manage.py test --no-input --shuffle
